### ISSUE TITLE
ERROR: This container was built for CPUs supporting at least the AVX instruction set

### ISSUE THREAD

**Issue by anbello** [NVIDIA/object-detection-tensorrt-example#2]
I followed the instruction and the dockerfile was built without problems but when I start the container I see the following:

```
ERROR: This container was built for CPUs supporting at least the AVX instruction set, but
       the CPU detected was Intel(R) Xeon(R) CPU           X3470  @ 2.93GHz, which does not report
       support for AVX.  An Illegal Instrution exception at runtime is likely to result.
       See https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX .

```

Is it possible to build without AVX extensions? Is there some parameter I can use to do this?

**Comment by GLBurnett** [comment]
Hey @anbello 

It looks like the AVX instruction set was [added to Intel CPUs around 2011](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions). It looks like the CPU you're using was released in 2009 and therefore doesn't support AVX. I don't believe there is a way around this other than using a newer CPU. The backwards compatibility of this container, and the packages inside, doesn't quite stretch that far back. Sorry!
