### ISSUE TITLE
PyCUDA ERROR: The context stack was not empty upon module cleanup.

### ISSUE THREAD

**Issue by kartoshhka** [NVIDIA/object-detection-tensorrt-example#3]
Hello!
I ran the script ./setup_environment.sh and it successfully built the TensorRT container.

Then I tried to run detect_objects_webcam.py, but got this PyCUDA error:
![изображение](https://user-images.githubusercontent.com/41269229/60599541-51e44080-9db7-11e9-880c-2d1b6b72aadc.png)
As you can see, the program even started detecting some objects, but then interrupted.

Could you please help to solve this?

(PS: Ubuntu 18.04 and CUDA 10.1)

**Comment by kartoshhka** [comment]
Ok, it seems program can't connect to X11.

**Comment by adrianosantospb** [comment]
> Ok, it seems program can't connect to X11.

How do you solve this?

**Comment by kartoshhka** [comment]
@adrianosantospb I ran it on the server, so in my case program just didn't see any display. To solve this I added X11 forwarding settings on server.

**Comment by adrianosantospb** [comment]
How did you do?

**Comment by kartoshhka** [comment]
@adrianosantospb 
**On the server** (my was Ubuntu 18.04):
in file ```/etc/ssh/sshd_config``` uncomment lines:

```
X11Forwarding yes
X11DisplayOffset 10
X11UseLocalhost yes
```

then restart the service:

```systemctl restart sshd.service```

**On the client machine** (my is Ubuntu 16.04):
Connect to server with -X attribute:

```ssh -X remoteuser@remotehost```

and try to launch any desktop program, e.g.:

```gedit```

**Comment by Siddhu68825** [comment]
I am too facing same issue.  After uncommenting the lines of X11, same issue.   Can any one suggest me a solution for this. Thanks in advance.

**Comment by MarritS** [comment]
I have the same problem when trying to start the program at boot through crontab. When I run it normally through terminal I don't have any issue.

**Comment by rgwangcn** [comment]
I have the same problem in pycuda, waiting for solution
